----------------------
Exception info:
<class 'IsADirectoryError'>
[Errno 21] Is a directory: 'user/1020'
Traceback (most recent call last):
  File "/home/jesse/Documents/GitHub/nlp-stat-test/testing/run.py", line 1302, in download_zip
    with zipfile.ZipFile(zip_file,'w') as zip:
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: 'user/1020'
